### ISSUE TITLE
Viewing on heroku deployment requires key to be binary

### ISSUE THREAD

**Issue by ArticPanda43** [ankane/lockbox#48]
`2020-05-26T23:28:32.474964+00:00 app[web.1]: I, [2020-05-26T23:28:32.474884 #4]  INFO -- : [4cff2ecd-3543-4cc3-aad3-4c88606653b1] Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)
2020-05-26T23:28:32.476537+00:00 app[web.1]: F, [2020-05-26T23:28:32.476463 #4] FATAL -- : [4cff2ecd-3543-4cc3-aad3-4c88606653b1]   
2020-05-26T23:28:32.476776+00:00 app[web.1]: F, [2020-05-26T23:28:32.476692 #4] FATAL -- : [4cff2ecd-3543-4cc3-aad3-4c88606653b1] Lockbox::Error (Key must use binary encoding):
2020-05-26T23:28:32.476912+00:00 app[web.1]: F, [2020-05-26T23:28:32.476806 #4] FATAL -- : [4cff2ecd-3543-4cc3-aad3-4c88606653b1]   
2020-05-26T23:28:32.477081+00:00 app[web.1]: F, [2020-05-26T23:28:32.476982 #4] FATAL -- : [4cff2ecd-3543-4cc3-aad3-4c88606653b1] vendor/bundle/ruby/2.5.0/gems/lockbox-0.4.2/lib/lockbox/utils.rb:39:in `decode_key'
2020-05-26T23:28:32.477081+00:00 app[web.1]: [4cff2ecd-3543-4cc3-aad3-4c88606653b1] vendor/bundle/ruby/2.5.0/gems/lockbox-0.4.2/lib/lockbox/key_generator.rb:14:in `attribute_key'
2020-05-26T23:28:32.477083+00:00 app[web.1]: [4cff2ecd-3543-4cc3-aad3-4c88606653b1] vendor/bundle/ruby/2.5.0/gems/lockbox-0.4.2/lib/lockbox.rb:84:in `attribute_key'
2020-05-26T23:28:32.477083+00:00 app[web.1]: [4cff2ecd-3543-4cc3-aad3-4c88606653b1] vendor/bundle/ruby/2.5.0/gems/lockbox-0.4.2/lib/lockbox/utils.rb:15:in `build_box'
2020-05-26T23:28:32.477084+00:00 app[web.1]: [4cff2ecd-3543-4cc3-aad3-4c88606653b1] vendor/bundle/ruby/2.5.0/gems/lockbox-0.4.2/lib/lockbox/model.rb:327:in `block (3 levels) in encrypts'
2020-05-26T23:28:32.477084+00:00 app[web.1]: [4cff2ecd-3543-4cc3-aad3-4c88606653b1] vendor/bundle/ruby/2.5.0/gems/lockbox-0.4.2/lib/lockbox/model.rb:246:in `block (3 levels) in encrypts'
2020-05-26T23:28:32.477084+00:00 app[web.1]: [4cff2ecd-3543-4cc3-aad3-4c88606653b1] vendor/bundle/ruby/2.5.0/gems/lockbox-0.4.2/lib/lockbox/model.rb:224:in `block (3 levels) in encrypts'
2020-05-26T23:28:32.477085+00:00 app[web.1]: [4cff2ecd-3543-4cc3-aad3-4c88606653b1] vendor/bundle/ruby/2.5.0/gems/blind_index-2.0.1/lib/blind_index/model.rb:77:in `block (4 levels) in blind_index'`

This is the error log i get when i try to run the controller method to create a new user on heroku. Everything works fine on my local machine but when viewing it on heroku it says that the key needs to use binary encoding.  Do you have a guide on how to get it working on heroku? i am also using Blind_index, after you showed me how to use the original field names from earlier on your website.

**Comment by ankane** [comment]
Hey @ArticPanda43, check out #45. I just pushed a new release with what was discussed in that issue.

**Comment by ArticPanda43** [comment]
You are an amazing person.
