### ISSUE TITLE
Integrating with Sorcery

### ISSUE THREAD

**Issue by flippakitten** [ankane/lockbox#49]
Hello,

I've run into an issue where login is failing while using the Sorcery GEM (Authentication) and `lockbox` (which is really nice, thank you).

I haven't dug very deep but was wondering if anyone has any insight into the cause?

Thank you,
James

Error:
```
PG::UndefinedColumn: ERROR: column users.email does not exist LINE 1: SELECT "users".* FROM "users" WHERE "users"."email" = 'test@... ^ 
```

I have use `blind_index` and can query `User.where(email: 'test@example.com')`

The stack trace is:
```
activerecord (6.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:744:in `prepare'
activerecord (6.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:744:in `block in prepare_statement'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:739:in `prepare_statement'
activerecord (6.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `exec_cache'
activerecord (6.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:658:in `execute_and_clear'
activerecord (6.0.3) lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `exec_query'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/database_statements.rb:493:in `select_prepared'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/database_statements.rb:68:in `select_all'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/query_cache.rb:105:in `block in select_all'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/query_cache.rb:122:in `block in cache_sql'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/query_cache.rb:113:in `cache_sql'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/query_cache.rb:105:in `select_all'
activerecord (6.0.3) lib/active_record/querying.rb:46:in `find_by_sql'
activerecord (6.0.3) lib/active_record/relation.rb:821:in `block in exec_queries'
activerecord (6.0.3) lib/active_record/relation.rb:839:in `skip_query_cache_if_necessary'
activerecord (6.0.3) lib/active_record/relation.rb:808:in `exec_queries'
activerecord (6.0.3) lib/active_record/relation.rb:626:in `load'
activerecord (6.0.3) lib/active_record/relation.rb:250:in `records'
activerecord (6.0.3) lib/active_record/relation.rb:245:in `to_ary'
activerecord (6.0.3) lib/active_record/relation/finder_methods.rb:527:in `find_nth_with_limit'
activerecord (6.0.3) lib/active_record/relation/finder_methods.rb:512:in `find_nth'
activerecord (6.0.3) lib/active_record/relation/finder_methods.rb:120:in `first'
sorcery (0.15.0) lib/sorcery/adapters/active_record_adapter.rb:72:in `find_by_credentials'
sorcery (0.15.0) lib/sorcery/model.rb:97:in `authenticate'
sorcery (0.15.0) lib/sorcery/controller.rb:40:in `login'
app/controllers/sessions_controller.rb:10:in `create'
actionpack (6.0.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.3) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.3) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.3) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (6.0.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by ankane** [comment]
Hey @flippakitten, it looks like Sorcery uses Arel instead of Active Record to construct queries, so it's querying on the `email` column instead of the blind index column.

https://github.com/Sorcery/sorcery/blob/6ba63a4ff600b804b8072e06f5cf0782fb701f5a/lib/sorcery/adapters/active_record_adapter.rb#L55-L73

You'd need to override the `find_by_credentials` method. From what I can tell, there's not a supported way to do it, so you'd need to create an initializer with something like:

```ruby
module CustomCredentials
  def find_by_credentials(credentials)
    @klass.find_by(email: credentials[0])
  end
end

ActiveSupport.on_load(:active_record) do
  ActiveRecord::Base.sorcery_adapter.singleton_class.prepend(CustomCredentials)
end
```

(you'd need to make it a bit more complex if you have multiple models that use Sorcery or multiple username attributes)

**Comment by flippakitten** [comment]
Thanks for the quick and detailed reponse, I really appreciate it.

At the moment I'm using the stock standard implementations, so nothing advanced yet.
I'll implent this and confirm it works (which it looks like it will) or post the final solution.

**Comment by flippakitten** [comment]
@ankane Thanks again confirmed the solution provided above works with a generic inistallation. I suspect I will need to make it more complex as I build things out but if I figure out a better way down the line I'll be back.

Thanks again.

(p.s. your github is a very impressive, so many things I want to use)

**Comment by ankane** [comment]
No problem, and thanks!
