### ISSUE TITLE
requiring lockbox when using only some parts of ActiveSupport results in error

### ISSUE THREAD

**Issue by bonybrown** [ankane/lockbox#65]
In a non-rails app ( for example, an AWS Lambda) where some parts of Active Support are imported for convenience functions, requiring `lockbox`  results in a NameError.

**Reproduction:**
With these gems:
```bash
gem install lockbox
gem install activesupport
```
Then:
```ruby
require 'active_support/core_ext/object'
require 'lockbox'
```
Results in:
```
Traceback (most recent call last):
       12: from /var/lang/bin/irb:23:in `<main>'
       11: from /var/lang/bin/irb:23:in `load'
       10: from /var/lang/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        9: from (irb):11
        8: from /var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        7: from /var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        6: from /var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        5: from /var/runtime/gems/lockbox-0.4.7/lib/lockbox.rb:23:in `<top (required)>'
        4: from /var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        3: from /var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        2: from /var/runtime/gems/lockbox-0.4.7/lib/lockbox/log_subscriber.rb:1:in `<top (required)>'
        1: from /var/runtime/gems/lockbox-0.4.7/lib/lockbox/log_subscriber.rb:2:in `<module:Lockbox>'
NameError (uninitialized constant ActiveSupport::LogSubscriber)
```

Perhaps https://github.com/ankane/lockbox/blob/master/lib/lockbox.rb#L23-L24 needs a guard around it that checks for `defined?( ActiveSupport::LogSubscriber )` ?

**Comment by ankane** [comment]
Hey @bonybrown, thanks for the great description. Should be fixed on master.

**Comment by bonybrown** [comment]
Thanks - confirmed working with gem from git master.
