### ISSUE TITLE
ActiveRecord::RecordNotSaved: Failed to save the record

### ISSUE THREAD

**Issue by pboling** [ankane/lockbox#84]
When migrating a large database table with lots of old data, some of which may no longer be valid according to the current model definition, is there a way built-in to Lockbox to "skip", or "delete", or otherwise run some custom failure callback, on records that are not valid?  Right now it seems to just blow up the migration (`Lockbox.migrate(klass)`), with no way around the issue.

**Comment by ankane** [comment]
Hey @pboling, Lockbox should skip validations when migrating: https://github.com/ankane/lockbox/blob/a1e4c0ac7d1a9b723190392327fa58f9779336f1/lib/lockbox/migrator.rb#L165

**Comment by pboling** [comment]
Interesting.  I think the issue is that something other than a validation is causing the failure to save, and I have no idea what that might be, but the bang on the save (`!`) is causing it to raise.

Here is the stack trace:
```
ActiveRecord::RecordNotSaved: Failed to save the record
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:308:in `save!'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:52:in `save!'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `block in save!'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `save!'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/suppressor.rb:48:in `save!'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:165:in `block (2 levels) in migrate_records'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:164:in `each'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:164:in `block in migrate_records'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:194:in `block in with_transaction'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:193:in `with_transaction'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:163:in `migrate_records'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:95:in `block in perform'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:102:in `block in each_batch'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:222:in `loop'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:101:in `each_batch'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:94:in `perform'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox/migrator.rb:34:in `migrate'
/usr/local/rvm/gems/ruby-2.5.7/gems/lockbox-0.4.9/lib/lockbox.rb:59:in `migrate'
/home/app/api/app/workers/data_cleanup/lockbox_backfill_worker.rb:39:in `perform'
```

**Comment by ankane** [comment]
Yeah, it's designed to fail loudly so you don't end up with unmigrated records. I'd try finding the record that's causing it to see what the issue is.

**Comment by pboling** [comment]
@ankane The problem is caused by acts_as_paranoid.  Migrating deleted data isn't possible without some fancy hacking.  Working on a solution, and will post here.  Apparently the root cause is in ActiveRecord preventing saving of a record that is `destroyed? # => true`
https://github.com/ActsAsParanoid/acts_as_paranoid/issues/145

**Comment by ankane** [comment]
Thanks for the update. fwiw, `migrate` also takes a relation if you just want to migrate live records for now:

```ruby
Lockbox.migrate(User.all)
```

(example assumes there's a default scope, but you can customize as needed)

**Comment by pboling** [comment]
I have to encrypt it all, so doing it part-way isn't going to be sufficient.

The solution I have found is to use [the `migrate_record` branch of my fork of lockbox](https://github.com/pboling/lockbox/tree/migrate_record) which simply adds a `migrate_record` method which is called for each record, and then to decorate that method with error handling using my [`debug_logging` gem](https://github.com/pboling/debug_logging/), like so:

```
module Lockbox
  class Migrator
    extend DebugLogging
    include DebugLogging::InstanceLogger.new(
      i_methods: [:migrate_record],
      config: {
        args_to_s_proc: ->(*record) { r = record.flatten.first; "Encrypted #{r.class} id: #{r.id}" },
        error_handler_proc: ->(config, error, _obj, _method_name, args) {
          record = args.first
          if error.class.to_s == "ActiveRecord::RecordNotSaved" && error.message =~ /Failed to save the record/ && record.errors.full_messages == []
            # The record failed due to acts_as_paranoid, and ActiveRecord
            #   https://github.com/ActsAsParanoid/acts_as_paranoid/issues/145
            # So we have to recover the deleted record first, then save it for encrypting, then re-delete it.
            result = record.recover(recursive: false, raise_error: false)
            config.log("Recovered *deleted* #{record.class} id: #{record.id} => #{result}")
            result = record.save!(validate: false)
            config.log("Encrypted *deleted* #{record.class} id: #{record.id} => #{result}")
            record.destroy
            config.log("Re-deleted *deleted* #{record.class} id: #{record.id}")
          else
            config.log("#{error.class}: #{error.message} for #{record.id}\nFull messages: #{record.errors.full_messages}")
            raise error
          end
        },
        logger: Logger.new($stdout)
      }
    )
  end
end
```

The added error handling undeletes the deleted record, saves it in order to encrypt it, and then re-deletes it.
It resulted in the following output:
```
D, [2020-12-19T01:55:21.357771 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 2) ~47033826247000@342921.3576~ debug: {}
D, [2020-12-19T01:55:21.510972 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 3) ~47033825479320@342921.5109~ debug: {}
D, [2020-12-19T01:55:21.623836 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 4) ~47033825215740@342921.6237~ debug: {}
D, [2020-12-19T01:55:21.727191 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 5) ~47033824976340@342921.7271~ debug: {}
D, [2020-12-19T01:55:21.838606 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 6) ~47033824693800@342921.8385~ debug: {}
D, [2020-12-19T01:55:22.055671 #10375] DEBUG -- : Recovered *deleted* Location id: 6 => true
D, [2020-12-19T01:55:22.158236 #10375] DEBUG -- : Encrypted *deleted* Location id: 6 => true
D, [2020-12-19T01:55:22.159783 #10375] DEBUG -- : Re-deleted *deleted* Location id: 6
...
```

**Comment by ankane** [comment]
Great, this should be helpful for others.

Another (hacky) idea would be to remove the `acts_as_paranoid` gem from a single console server and run it there (then kill the server).
