### ISSUE TITLE
uninitialized constant OpenSSL::KDF

### ISSUE THREAD

**Issue by escoffon** [ankane/lockbox#9]
Some openssl distributions don't export the OpenSSL::KDF symbol, and therefore the check in KeyGenerator#hkdf crashes. Here is output from one of my test cases:

```
  1) Opo::Document::Base#initialize should accept owner, title, note, and contents
     Failure/Error: rv = super(attrs)
     
     NameError:
       uninitialized constant OpenSSL::KDF
     # /usr/local/rvm/gems/ruby-2.4.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant'
     # /usr/local/rvm/gems/ruby-2.4.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
     # /usr/local/rvm/gems/ruby-2.4.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
     # /usr/local/rvm/gems/ruby-2.4.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
     # /Users/escoffon/src/gems/lockbox/lib/lockbox/key_generator.rb:37:in `hkdf'
     # /Users/escoffon/src/gems/lockbox/lib/lockbox/key_generator.rb:14:in `attribute_key'
     # /Users/escoffon/src/gems/lockbox/lib/lockbox.rb:134:in `attribute_key'
     # /Users/escoffon/src/gems/lockbox/lib/lockbox/utils.rb:14:in `build_box'
     # /Users/escoffon/src/gems/lockbox/lib/lockbox/active_storage_extensions.rb:18:in `encrypt_attachable'
     # /Users/escoffon/src/gems/lockbox/lib/lockbox/active_storage_extensions.rb:55:in `attach'
     # /usr/local/rvm/gems/ruby-2.4.0/gems/activestorage-5.2.3/lib/active_storage/attached/macros.rb:37:in `contents='
     # ./app/models/opo/document/base.rb:133:in `initialize'
     # ./app/models/opo/document/text.rb:16:in `initialize'
     # ./spec/models/opo/document/base_spec.rb:37:in `block (3 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # NameError:
     #   uninitialized constant OpenSSL::KDF
     #   /usr/local/rvm/gems/ruby-2.4.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
```
PR #8 has a fix where I first check if OpenSSL::KDF exists, and then if it exports `hkdf`

**Comment by ankane** [comment]
Fixed in #8
